#!/usr/bin/bash


red=$'\e[1;31m' # red colour 
green=$'\e[1;32m' # green colour
blue=$'\e[1;34m' # blue colour
orange=$'\e[1;33m' # orange colour

printf "Enter Kernel Parameter name:"

read parameter




# Shared Memory

if [ "$parameter" == sem ];then
	echo "sem = > Semaphore values:is yet another mechanism for support of thread or process synchronization."
	printf "Do you want to change value of sem paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/sem | awk '{print $1}'`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.sem=$value
			echo "$green Kernel.sem paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi



if [ "$parameter" == msgmnb ];then
	echo "msgmnb = > Maximum message queue in bytes"
	printf "Do you want to change value of sem paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/sem | awk '{print $1}'`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.msgmnb=$value
			echo "$green Kernel.sem paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi







if [ "$parameter" == msgmni ];then
	echo "msgmni = > Maximum allowed message queue identifiers"
	printf "Do you want to change value of msgmni paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/msgmni | awk '{print $1}'`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.msgmni=$value
			echo "$green Kernel.msgmni paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi



if [ "$parameter" == msgmax ];then
	echo "msgmax = > Maximum message size in bytes"
	printf "Do you want to change value of msgmax paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/msgmax | awk '{print $1}'`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.msgmax=$value
			echo "$green Kernel.msgmax paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi



if [ "$parameter" == shmmni ];then
	echo "shmmni = > Number of shared segments system-wide"
	printf "Do you want to change value of shmmni paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/shmmni | awk '{print $1}'`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.shmmni=$value
			echo "$green Kernel.shmmni paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi




if [ "$parameter" == shmall ];then
	echo "shmall = > Shared memory system-wide in pages"
	printf "Do you want to change value of shmall paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/shmall | awk '{print $1}'`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.shmall=$value
			echo "$green Kernel.shmall paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi



if [ "$parameter" == shmmax ];then
	echo "shmmax = > Shared segment size in bytes"
	printf "Do you want to change value of shmmax paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/shmmax | awk '{print $1}'`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.shmmax=$value
			echo "$green Kernel.shmmax paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi



# Processes


if [ "$parameter" == threads-max ];then
	echo "threads-max = > Maximum threads allowed in the system"
	printf "Do you want to change value of threads-max paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/threads-max | awk '{print $1}'`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.threads-max=$value
			echo "$green Kernel.threads-max paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi


# Signals


if [ "$parameter" == rtsig-max ];then
	echo "rtsig-max = > Maximum real-time signals"
	printf "Do you want to change value of rtsig-max paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/rtsig-max | awk '{print $1}'`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.rtsig-max=$value
			echo "$green Kernel.rtsig-max paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi

if [ "$parameter" == rtsig-nr ];then
	echo "rtsig-nr = > Number of currently queued real-time signals"
	printf "Do you want to change value of rtsig-nr paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/rtsig-nr | awk '{print $1}'`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.rtsig-nr=$value
			echo "$green Kernel.rtsig-nr paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi





# Profiling/Debugging

if [ "$parameter" == sysrq ];then
	echo "sysrq = > System trace request"
	printf "Do you want to change value of sysrq paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/sysrq | awk '{print $1}'`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.sysrq=$value
			echo "$green Kernel.sysrq paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi

if [ "$parameter" == printk ];then
	echo "printk = > Printk values [For More Info Press i ]"
	printf "Do you want to change value of printk paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/printk`
		echo "$blue current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.printk=$value
			echo "$green Kernel.printk paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	elif [ "$response" == i ];then
		echo "$orange printk parameter has four fields: console_loglevel, default_message_ loglevel,
		minimum_console_level, and default_console_level. Messages with a higher priority than
		console_loglevel are printed to the console. Messages without an explicit priority are
		printed with default_message_loglevel priority. The minimum (highest) value to which
		console_loglevel can be set is determined by the minimum_console_level parameter. The
		default_console_loglevel is the default value for console_loglevel."
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi





# System



if [ "$parameter" == domainname ];then
	echo "domainname = > Domain name"
	printf "Do you want to change value of domainname paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/domainname`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.domainname=$value
			echo "$green Kernel.domainname paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi





if [ "$parameter" == hostname ];then
	echo "hostname => Host name"
	printf "Do you want to change value of hostname paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/hostname`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.hostname=$value
			echo "$green Kernel.hostname paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi





if [ "$parameter" == ostype ];then
	echo "ostype = > Operating system type"
	printf "Do you want to change value of ostype paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/ostype`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.ostype=$value
			echo "$green Kernel.ostype paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi








if [ "$parameter" == osrelease ];then
	echo "osrelease = > Operating system release"
	printf "Do you want to change value of osrelease paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/osrelease`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.osrelease=$value
			echo "$green Kernel.osrelease paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi




if [ "$parameter" == real-root-dev ];then
	echo "real-root-dev = > Real root device partition"
	printf "Do you want to change value of real-root-dev paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/real-root-dev`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.real-root-dev=$value
			echo "$green Kernel.real-root-dev paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi

if [ "$parameter" == version ];then
	echo "version = > Kernel version"
	printf "Do you want to change value of version paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/kernel/version`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w kernel.version=$value
			echo "$green Kernel.version paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi


# Virtual Memory
# Sysctl Prefix: vm
# /proc Prefix: /proc/sys/vm/



if [ "$parameter" == max_map_count ];then
	echo "max_map_count = > Maximum number of memory map areas per process"
	printf "Do you want to change value of max_map_count paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/vm/max_map_count`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w vm.max_map_count=$value
			echo "$green Kernel.max_map_count paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi



if [ "$parameter" == min-readahead ];then
	echo "min-readahead = > Maximum I/O read-ahead size"
	printf "Do you want to change value of min-readahead paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/vm/min-readahead`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w vm.min-readahead=$value
			echo "$green Kernel.min-readahead paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi



if [ "$parameter" == max-readahead ];then
	echo "max-readahead = > Minimum I/O read-ahead size"
	printf "Do you want to change value of max-readahead paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/vm/max-readahead`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w vm.max-readahead=$value
			echo "$green Kernel.max-readahead paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi

fi

if [ "$parameter" == vm.heap-stack-gap ];then
	echo "vm.heap-stack-gap = > Enforces a gap between heap and stack [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo """$orange parameter allows a gap to be enforced between the heap and the stack.
	       	Any access to memory in the gap area causes a segmentation fault.
	       	This action avoids silent corruption that could occur when allocating on stack runs over
		the heap. The gap enforced is in number of pages."""
	else

		printf "Do you want to change value of vm.heap-stack-gap paramater?(y/n)"
		read response

		if [ "$response" == y ];then
			current_parameter=`cat /proc/sys/vm/vm.heap-stack-gap`
			echo "current value is $current_parameter"
			printf "Enter value you want:"
			read value
			if [ "$value" ];then
				sudo sysctl -w vm.vm.heap-stack-gap=$value
				echo "$green Kernel.vm.heap-stack-gap paramater changed [ OK ]"
			else
				echo "$orange Please Enter Valid Number"
			fi
		elif [ "$response" == n ];then
			echo "$blue You Dont want to change The value"
		else
			echo "$red Please Enter valid Value!!!"
		fi
	fi
fi





if [ "$parameter" == pagetable_cache ];then
	echo "pagetable_cache = > Cache size per processor for page tables [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo """$orange The pagetable_cache parameter specifies low and high cache size per processor to be
		used for page tables. On SMP systems, this parameter allows the system to do fast
		pagetable allocations without having to acquire the vm memory lock. On a
		single-CPU system, these values can be set to 0 to avoid wasting memory."""
	else

		printf "Do you want to change value of pagetable_cache paramater?(y/n)"
		read response

		if [ "$response" == y ];then
			current_parameter=`cat /proc/sys/vm/pagetable_cache`
			echo "current value is $current_parameter"
			printf "Enter value you want:"
			read value
			if [ "$value" ];then
				sudo sysctl -w vm.pagetable_cache=$value
				echo "$green Kernel.pagetable_cache paramater changed [ OK ]"
			else
				echo "$orange Please Enter Valid Number"
			fi
		elif [ "$response" == n ];then
			echo "$blue You Dont want to change The value"
		else
			echo "$red Please Enter valid Value!!!"
		fi
	fi
fi

if [ "$parameter" == page_cluster ];then
	echo "page_cluster = > Pages to read on a page fault [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo """$orange The page_cluster parameter is used to determine the number of pages the vm can
		read at once on a page fault. The number of pages is 2 ^ page_cluster. This VM
		subsystem tries to reduce excessive seeks by reading multiple pages on a page
		fault."""
	else

		printf "Do you want to change value of page_cluster paramater?(y/n)"
		read response

		if [ "$response" == y ];then
			current_parameter=`cat /proc/sys/vm/page_cluster`
			echo "current value is $current_parameter"
			printf "Enter value you want:"
			read value
			if [ "$value" ];then
				sudo sysctl -w vm.page_cluster=$value
				echo "$green Kernel.page_cluster paramater changed [ OK ]"
			else
				echo "$orange Please Enter Valid Number"
			fi
		elif [ "$response" == n ];then
			echo "$blue You Dont want to change The value"
		else
			echo "$red Please Enter valid Value!!!"
		fi
	fi
fi

if [ "$parameter" == kswapd ];then
	echo "kswapd = > Swaps out memory pages to disk [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo """$orange The vm swapout daemon, kswapd, swaps out pages to disk when memory gets
		fragmented or full. This is a three-field value that corresponds to tries_base, tries_min,
		and swap_cluster.
		The maximum number of pages kswapd tries to free at once is determined by the
		tries_base field. This number is divided by 4 or 8 to determine the number of pages
		(mm/vmscan.c).
		The tries_min field specifies the minimum number of pages kswapd tries to free each
		time it is called.
		The swap_cluster field is the number of pages kswapd writes in one turn. Keeping this
		value large ensures that kswapd does its I/O in large chunks and that the disk
	doesn't have to seek often. If it is too large, it may cause request queue flooding."""
	
	else
		printf "Do you want to change value of kswapd paramater?(y/n)"
		read response

		if [ "$response" == y ];then
			current_parameter=`cat /proc/sys/vm/kswapd`
			echo "current value is $current_parameter"
			printf "Enter value you want:"
			read value
			if [ "$value" ];then
				sudo sysctl -w vm.kswapd=$value
				echo "$green Kernel.kswapd paramater changed [ OK ]"
			else
				echo "$orange Please Enter Valid Number"
			fi
		elif [ "$response" == n ];then
			echo "$blue You Dont want to change The value"
		else
			echo "$red Please Enter valid Value!!!"
		fi
	fi
fi


if [ "$parameter" == bdflush ];then
	echo "bdflush = > Dirty page handling [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo """$orange 
		1 - The first field, nfract, determines the percentage of dirty buffer cache to activate
		bdflush. A higher value can delay disk writes for a longer time but will have to do alot of I/O when memory becomes short.
	       	A lower value spreads I/O more evenly at the cost of frequent I/O operations. The default value is 50%.
		2 - The second field, ndirty, is the maximum number of dirty blocks that bdflush can
		write to disk at once. A higher value can delay I/O and can lead to I/O burst,
		whereas a lower value can lead to a memory shortage as bdflush isn't awakened frequently enough.
		3 - The third field, nrefill, is the number of buffers that to the list of free buffers when refill is called.
		The fourth field,nref_dirt,bdflushTRies to obtain and add is the dirty buffer threshold for activating bdflush.
		The sixth field, age_buffer, is the maximum time before writing out a dirty normal buffer to disk. The value is in jiffies.
		The seventh field, age_super, is the maximum time before writing out a dirty super block buffer to disk."""
	else

		printf "Do you want to change value of bdflush paramater?(y/n)"
		read response

		if [ "$response" == y ];then
			current_parameter=`cat /proc/sys/vm/bdflush`
			echo "current value is $current_parameter"
			printf "Enter value you want:"
			read value
			if [ "$value" ];then
				sudo sysctl -w vm.bdflush=$value
				echo "$green Kernel.bdflush paramater changed [ OK ]"
			else
				echo "$orange Please Enter Valid Number"
			fi
		elif [ "$response" == n ];then
			echo "$blue You Dont want to change The value"
		else
			echo "$red Please Enter valid Value!!!"
		fi
	fi
fi


if [ "$parameter" == vm_passes ];then
	echo "vm_passes = > Memory balancing [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo """$orange 
		The vm_passes parameter is the number of vm passes before failing the memory balancing."""
	
	else
		printf "Do you want to change value of vm_passes paramater?(y/n)"
		read response

		if [ "$response" == y ];then
			current_parameter=`cat /proc/sys/vm/vm_passes`
			echo "current value is $current_parameter"
			printf "Enter value you want:"
			read value
			if [ "$value" ];then
				sudo sysctl -w vm.vm_passes=$value
				echo "$green Kernel.vm_passes paramater changed [ OK ]"
			else
				echo "$orange Please Enter Valid Number"
			fi
		elif [ "$response" == n ];then
			echo "$blue You Dont want to change The value"
		else
			echo "$red Please Enter valid Value!!!"
		fi
	fi
fi





if [ "$parameter" == vm_mapped_ratio ];then
	echo "vm_mapped_ratio = > Pageout rate [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo """$orange 
		The vm_mapped_ratio parameter determines the pageout rate. A smaller value indicates
		an early start to pageout."""
	
	else
		printf "Do you want to change value of vm_mapped_ratio paramater?(y/n)"
		read response

		if [ "$response" == y ];then
			current_parameter=`cat /proc/sys/vm/vm_mapped_ratio`
			echo "current value is $current_parameter"
			printf "Enter value you want:"
			read value
			if [ "$value" ];then
				sudo sysctl -w vm.vm_mapped_ratio=$value
				echo "$green Kernel.vm_mapped_ratio paramater changed [ OK ]"
			else
				echo "$orange Please Enter Valid Number"
			fi
		elif [ "$response" == n ];then
			echo "$blue You Dont want to change The value"
		else
			echo "$red Please Enter valid Value!!!"
		fi
	fi
fi













if [ "$parameter" == vm_lru_balance_ratio ];then
	echo "vm_lru_balance_ratio = > Active and inactive cache ratio [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo """$orange 
		The vm_lru_balance_ratio parameter determines the balance between active and
		inactive cache. A bigger value means active cache grows as active cache is rotated
		slowly."""
	
	else
		printf "Do you want to change value of vm_lru_balance_ratio paramater?(y/n)"
		read response

		if [ "$response" == y ];then
			current_parameter=`cat /proc/sys/vm/vm_lru_balance_ratio`
			echo "current value is $current_parameter"
			printf "Enter value you want:"
			read value
			if [ "$value" ];then
				sudo sysctl -w vm.vm_lru_balance_ratio=$value
				echo "$green Kernel.vm_lru_balance_ratio paramater changed [ OK ]"
			else
				echo "$orange Please Enter Valid Number"
			fi
		elif [ "$response" == n ];then
			echo "$blue You Dont want to change The value"
		else
			echo "$red Please Enter valid Value!!!"
		fi
	fi
fi






if [ "$parameter" == vm_cache_scan_ratio ];then
	echo "vm_cache_scan_ratio = > LRU queue to scan in one go [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo """$orange 
		The vm_cache_scan_ratio parameter specifies how much of inactive LRU queue is
		scanned in one go. A value of 6 implies that a scan of 1/6 of the inactive list is done."""
	
	else
		printf "Do you want to change value of vm_cache_scan_ratio paramater?(y/n)"
		read response

		if [ "$response" == y ];then
			current_parameter=`cat /proc/sys/vm/vm_cache_scan_ratio`
			echo "current value is $current_parameter"
			printf "Enter value you want:"
			read value
			if [ "$value" ];then
				sudo sysctl -w vm.vm_cache_scan_ratio=$value
				echo "$green Kernel.vm_cache_scan_ratio paramater changed [ OK ]"
			else
				echo "$orange Please Enter Valid Number"
			fi
		elif [ "$response" == n ];then
			echo "$blue You Dont want to change The value"
		else
			echo "$red Please Enter valid Value!!!"
		fi
	fi
fi






if [ "$parameter" == vm_vfs_scan_ratio ];then
	echo "vm_vfs_scan_ratio = > VFS queues to scan in one go [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo """$orange 
		The vm_vfs_scan_ratio parameter specifies how much of VFS queues is scanned in one
		go. A value of 6 implies that 1/6 of the unused inode, dentry, and dquot caches will
		be freed."""
	
	else
		printf "Do you want to change value of vm_vfs_scan_ratio paramater?(y/n)"
		read response

		if [ "$response" == y ];then
			current_parameter=`cat /proc/sys/vm/vm_vfs_scan_ratio`
			echo "current value is $current_parameter"
			printf "Enter value you want:"
			read value
			if [ "$value" ];then
				sudo sysctl -w vm_vfs_scan_ratio=$value
				echo "$green Kernel.vm_vfs_scan_ratio paramater changed [ OK ]"
			else
				echo "$orange Please Enter Valid Number"
			fi
		elif [ "$response" == n ];then
			echo "$blue You Dont want to change The value"
		else
			echo "$red Please Enter valid Value!!!"
		fi
	fi
fi





if [ "$parameter" == vm_gfp_debug ];then
	echo "$vm_gfp_debug = > Enable to send debug messages to log"
	printf "Do you want to change value of vm_gfp_debug paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/vm/vm_gfp_debug`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w vm_gfp_debug=$value
			echo "$green Kernel.vm_gfp_debug paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


# File system
# Sysctl Prefix: fs
# /proc Prefix: /proc/sys/fs/



if [ "$parameter" == file-max ];then
	echo "file-max = > Maximum number of file descriptors [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo """$orange 
		The system file_descriptor limit is set using file-max. The descriptor limit is the
		maximum number of file descriptors that any one process may open at once."""
	
	else
		printf "Do you want to change value of file-max paramater?(y/n)"
		read response

		if [ "$response" == y ];then
			current_parameter=`cat /proc/sys/fs/file-max`
			echo "current value is $current_parameter"
			printf "Enter value you want:"
			read value
			if [ "$value" ];then
				sudo sysctl -w fs.file-max=$value
				echo "$green Kernel.file-max paramater changed [ OK ]"
			else
				echo "$orange Please Enter Valid Number"
			fi
		elif [ "$response" == n ];then
			echo "$blue You Dont want to change The value"
		else
			echo "$red Please Enter valid Value!!!"
		fi
	fi
fi


if [ "$parameter" == file-nr ];then
	echo "file-nr = > Number of file handles [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo """$orange 
		The file-nr has three fields: the number of allocated file handles, the number of used file
		handles, and the maximum number of file handles."""
	
	else
		printf "Do you want to change value of file-nr paramater?(y/n)"
		read response

		if [ "$response" == y ];then
			current_parameter=`cat /proc/sys/fs/file-nr`
			echo "current value is $current_parameter"
			printf "Enter value you want:"
			read value
			if [ "$value" ];then
				sudo sysctl -w fs.file-nr=$value
				echo "$green Kernel.file-nr paramater changed [ OK ]"
			else
				echo "$orange Please Enter Valid Number"
			fi
		elif [ "$response" == n ];then
			echo "$blue You Dont want to change The value"
		else
			echo "$red Please Enter valid Value!!!"
		fi
	fi
fi


if [ "$parameter" == inode-state ];then
	echo "inode-state = > Inode status "
	printf "Do you want to change value of inode-state paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/fs/inode-state`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w fs.inode-state=$value
			echo "$green Kernel.inode-state paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


if [ "$parameter" == inode-nr ];then
	echo "inode-nr = > Inode status"
	printf "Do you want to change value of inode-nr paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/fs/inode-nr`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w fs.inode-nr=$value
			echo "$green Kernel.inode-nr paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi

if [ "$parameter" == super-max ];then
	echo "super-max = > Maximum number of file systems [ For more Detail press i ]"
	read info
	if [ "$info" == i ];then
		echo """The super-max parameter controls the maximum number of super blocks and thus
	        determines the maximum number of mounted file systems the kernel can have. This
       		value needs to be increased if there is a need to mount more file systems than the
		current value in super-max."""
	fi
	printf "Do you want to change value of super-max paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/fs/super-max`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w fs.super-max=$value
			echo "$green Kernel.super-max paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


if [ "$parameter" == dentry-state ];then
	echo "dentry-state = > Status of directory cache"
	printf "Do you want to change value of dentry-state paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/fs/dentry-state`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w fs.dentry-state=$value
			echo "$green Kernel.dentry-state paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


if [ "$parameter" == dquot-nr ];then
	echo "dquot-nr = > Number of allocated and free disk quota entries"
	printf "Do you want to change value of dquot-nr paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/fs/dquot-nr`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w fs.dquot-nr=$value
			echo "$green Kernel.dquot-nr paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi

if [ "$parameter" == dquot-max ];then
	echo "dquot-max = > Maximum number of cached disk quota entries"
	printf "Do you want to change value of dquot-max paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/fs/dquot-max`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w fs.dquot-max=$value
			echo "$green Kernel.dquot-max paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi

if [ "$parameter" == dir-notify-enable ];then
	echo "dir-notify-enable = > Enables dnotify[For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo "$orange The dir-notify-enable field enables or disables the dnotify interface on a system-wide basis."
	fi
	printf "Do you want to change value of dir-notify-enable paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/fs/dir-notify-enable`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w fs.dir-notify-enable=$value
			echo "$green Kernel.dir-notify-enable paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi

if [ "$parameter" == aio-max-nr ];then
	echo "aio-max-nr = > Maximum number of AIO requests[For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo "$orange The aio-max-nr field enables or disables the dnotify interface on a system-wide basis."
	fi
	printf "Do you want to change value of aio-max-nr paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/fs/aio-max-nr`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w fs.aio-max-nr=$value
			echo "$green Kernel.aio-max-nr paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi

if [ "$parameter" == aio-nr ];then
	echo "aio-nr = > Number of AIO requests[For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo "$orange The aio-nr field enables or disables the dnotify interface on a system-wide basis."
	fi
	printf "Do you want to change value of aio-nr paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/fs/aio-nr`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w fs.aio-nr=$value
			echo "$green Kernel.aio-nr paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi

## NetWork


# Net Core

# => Sysctl Prefix: net.core
# => /proc Prefix: /proc/sys/net/core


if [ "$parameter" == hot_list_length ];then
	echo "hot_list_length = > Maximum number of skb-heads to be cached "
	printf "Do you want to change value of hot_list_length paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/vm/hot_list_length`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.hot_list_length=$value
			echo "$green Kernel.hot_list_length paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


if [ "$parameter" == optmem_max ];then
	echo "optmem_max = > Maximum ancillary buffer size per socket "
	printf "Do you want to change value of optmem_max paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/vm/optmem_max`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.optmem_max=$value
			echo "$green Kernel.optmem_max paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


if [ "$parameter" == message_burst ];then
	echo "message_burst = > Limits warning messages "
	printf "Do you want to change value of message_burst paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/vm/message_burst`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.message_burst=$value
			echo "$green Kernel.message_burst paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi

if [ "$parameter" == message_cost ];then
	echo "message_cost = > Limits warning messages "
	printf "Do you want to change value of message_cost paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/vm/message_cost`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.message_cost=$value
			echo "$green Kernel.message_cost paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi

if [ "$parameter" == netdev_max_backlog ];then
	echo "netdev_max_backlog = > Maximum number of packets queued "
	printf "Do you want to change value of netdev_max_backlog paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/vm/netdev_max_backlog`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.netdev_max_backlog=$value
			echo "$green Kernel.netdev_max_backlog paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi

if [ "$parameter" == rmem_default ];then
	echo "rmem_default = > Socket receive buffer size "
	printf "Do you want to change value of rmem_default paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/vm/rmem_default`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.rmem_default=$value
			echo "$green Kernel.rmem_default paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


if [ "$parameter" == wmem_default ];then
	echo "wmem_default = > Socket Send buffer size "
	printf "Do you want to change value of wmem_default paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/vm/wmem_default`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.wmem_default=$value
			echo "$green Kernel.wmem_default paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


if [ "$parameter" == rmem_max ];then
	echo "rmem_max = > Maximum receive socket buffer size "
	printf "Do you want to change value of rmem_max paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/vm/rmem_max`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.rmem_max=$value
			echo "$green Kernel.rmem_max paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


if [ "$parameter" == wmem_max ];then
	echo "wmem_max = > Maximum Send socket buffer size "
	printf "Do you want to change value of wmem_max paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/vm/wmem_max`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.wmem_max=$value
			echo "$green Kernel.wmem_max paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi




# ICMP

# Sysctl Prefix: net.ipv4
# /proc Prefix: /proc/sys/net/ipv4


if [ "$parameter" == icmp_ratemask ];then
	echo "icmp_ratemask = > Mask value for ICMP types [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo "$orange The icmp_ratemask parameter contains ICMP types for which rates are limited."
	fi
	printf "Do you want to change value of icmp_ratemask paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/icmp_ratemask`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.icmp_ratemask=$value
			echo "$green net.ipv4.icmp_ratemask paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi




if [ "$parameter" == icmp_ratelimit ];then
	echo "icmp_ratelimit = > Rate for sending ICMP Packets [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo "$orange The icmp_ratelimit parameter limits the maximum rates for sending ICMP packets
		whose type matches the icmp_ratemask parameter to specific targets. A value of 0
		disables any limit. The value is in jiffies."
	fi
	printf "Do you want to change value of icmp_ratelimit paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/icmp_ratelimit`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.icmp_ratelimit=$value
			echo "$green net.ipv4.icmp_ratelimit paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


if [ "$parameter" == icmp_ignore_bogus_error_responses ];then
	echo "icmp_ratelimit => Warning messages from router [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo "$orange If icmp_ignore_bogus_error_responses is enabled, the kernel does not issue any log
		warnings when routers send bogus responses to broadcast frames."
	fi
	printf "Do you want to change value of icmp_ratelimit paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.icmp_ignore_bogus_error_responses=$value
			echo "$green net.ipv4.icmp_ignore_bogus_error_responses paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi




if [ "$parameter" == icmp_echo_ignore_broadcasts ];then
	echo "icmp_ratelimit => ICMP echo requests to broadcast addresses [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo "$orange If icmp_echo_ignore_broadcasts is enabled, the kernel ignores all the
		ICMP echo requests sent to broadcast/multicast addresses."
	fi
	printf "Do you want to change value of icmp_ratelimit paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.icmp_echo_ignore_broadcasts=$value
			echo "$green net.ipv4.icmp_echo_ignore_broadcasts paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


if [ "$parameter" == icmp_echo_ignore_all ];then
	echo "icmp_ratelimit => ICMP echo requests [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo "$orange If the icmp_echo_ignore_all parameter is enabled, the kernel ignores all the ICMP echo
		requests sent to it."
	fi
	printf "Do you want to change value of icmp_ratelimit paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/icmp_echo_ignore_all`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.icmp_echo_ignore_all=$value
			echo "$green net.ipv4.icmp_echo_ignore_all paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi

if [ "$parameter" == igmp_max_membership ];then
	echo "icmp_ratelimit => Maximum number of multicast groups [For More Info press i ]"
	read info
	if [ "$info" == i ];then
		echo "$orange The igmp_max_membership parameter is the maximum number of multicast groups we
		can subscribe to."
	fi
	printf "Do you want to change value of icmp_ratelimit paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/igmp_max_membership`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.igmp_max_membership=$value
			echo "$green net.ipv4.igmp_max_membership paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi

## NEIGHBOR
#Sysctl Prefix: net.ipv4.neigh.interface
#/proc Prefix: /proc/sys/net/neigh/interface


if [ "$parameter" == locktime ];then
	echo "icmp_ratelimit => Time before replacing an old ARP entry "
	printf "Do you want to change value of locktime paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/neigh/enp1s0/locktime`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.neigh.enp1s0.locktime=$value
			echo "$green net.locktime paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi




if [ "$parameter" == proxy_delay ];then
	echo "proxy_delay => Maximum time before answering an ARP request"
	printf "Do you want to change value of proxy_delay paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/neigh/enp1s0/proxy_delay`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.neigh.enp1s0.proxy_delay=$value
			echo "$green net.proxy_delay paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi





if [ "$parameter" == anycast_delay ];then
	echo "anycast_delay => Maximum delay for neighbor solicitation messages"
	printf "Do you want to change value of anycast_delay paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/neigh/enp1s0/anycast_delay`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.neigh.enp1s0.anycast_delay=$value
			echo "$green net.anycast_delay paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi




if [ "$parameter" == proxy_qlen ];then
	echo "proxy_qlen => Maximum queue length of delayed proxy ARP"
	printf "Do you want to change value of proxy_qlen paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/neigh/enp1s0/proxy_qlen`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.neigh.enp1s0.proxy_qlen=$value
			echo "$green net.proxy_qlen paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


if [ "$parameter" == unres_qlen ];then
	echo "unres_qlen => Maximum queue length for pending ARP request"
	printf "Do you want to change value of unres_qlen paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/neigh/enp1s0/unres_qlen`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.neigh.enp1s0.unres_qlen=$value
			echo "$green net.unres_qlen paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi

if [ "$parameter" == gc_stale_time ];then
	echo "gc_stale_time => Time before a check for stale ARP entries"
	printf "Do you want to change value of gc_stale_time paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/neigh/enp1s0/gc_stale_time`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.neigh.enp1s0.gc_stale_time=$value
			echo "$green net.gc_stale_time paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi




if [ "$parameter" == delay_first_probe_time ];then
	echo "delay_first_probe_time => Delay for first probe if neighbor is reachable"
	printf "Do you want to change value of delay_first_probe_time paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/neigh/enp1s0/delay_first_probe_time`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.neigh.enp1s0.delay_first_probe_time=$value
			echo "$green net.delay_first_probe_time paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi



if [ "$parameter" == base_reachable_time ];then
	echo "base_reachable_time => Validity period of an entry once a neighbor has been found. Default is 30 seconds."
	printf "Do you want to change value of base_reachable_time paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/neigh/enp1s0/base_reachable_time`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.neigh.enp1s0.base_reachable_time=$value
			echo "$green net.base_reachable_time paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi





if [ "$parameter" == retrans_time ];then
	echo "retrans_time => Time between neighbor solicitation retransmits"
	printf "Do you want to change value of retrans_time paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/neigh/enp1s0/retrans_time`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.neigh.enp1s0.retrans_time=$value
			echo "$green net.retrans_time paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi




if [ "$parameter" == app_solicit ];then
	echo "app_solicit => Number of requests to send to user-level ARP daemon"
	printf "Do you want to change value of app_solicit paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/neigh/enp1s0/app_solicit`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.neigh.enp1s0.app_solicit=$value
			echo "$green net.app_solicit paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


if [ "$parameter" == ucast_solicit ];then
	echo "ucast_solicit => Maximum number of retries for unicast solicitation"
	printf "Do you want to change value of ucast_solicit paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/neigh/enp1s0/ucast_solicit`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.neigh.enp1s0.ucast_solicit=$value
			echo "$green net.ucast_solicit paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


if [ "$parameter" == mcast_solicit ];then
	echo "mcast_solicit => Maximum number of retries for multicast solicitation"
	printf "Do you want to change value of mcast_solicit paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/neigh/enp1s0/mcast_solicit`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.neigh.enp1s0.mcast_solicit=$value
			echo "$green net.mcast_solicit paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi










# CONFIG
# Sysctl Prefix: net.ipv4.conf.interfaceface



if [ "$parameter" == proxy_arp ];then
	echo "proxy_arp => Responds to ARP requests if enabled "
	printf "Do you want to change value of proxy_arp paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/conf/enp1s0/proxy_arp`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.conf.enp1s0.proxy_arp=$value
			echo "$green net.proxy_arp paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi



if [ "$parameter" == rp_filter ];then
	echo "rp_filter => Source validation is required if enabled "
	printf "Do you want to change value of rp_filter paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/conf/enp1s0/rp_filter`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.conf.enp1s0.rp_filter=$value
			echo "$green net.rp_filter paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi



if [ "$parameter" == bootp_relay ];then
	echo "bootp_relay => Accepts packets with 0.x.y.z addresses "
	printf "Do you want to change value of bootp_relay paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/conf/enp1s0/bootp_relay`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.conf.enp1s0.bootp_relay=$value
			echo "$green net.bootp_relay paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi




if [ "$parameter" == accept_source_route ];then
	echo "accept_source_route => Accepts set of IP addresses to visit on way"
	printf "Do you want to change value of accept_source_route paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/conf/enp1s0/accept_source_route`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.conf.enp1s0.accept_source_route=$value
			echo "$green net.accept_source_route paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi





if [ "$parameter" == send_redirects ];then
	echo "send_redirects => Sends ICMP redirects [ for more info press i ]"
	read info
	if [ "$info" == i ];then
		echo "$orange The send_redirects parameter determines whether such redirects are sent."
	fi

	printf "Do you want to change value of send_redirects paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/conf/enp1s0/send_redirects`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.conf.enp1s0.send_redirects=$value
			echo "$green net.send_redirects paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi




if [ "$parameter" == shared_media ];then
	echo "shared_media => Different subnet communication [ For more Info press i ] "
	read info
	if [ "" == "" ];then
		echo "$orange The shared_media parameter allows the kernel to assume that different subnets on this
		device can communicate directly."
	fi
	printf "Do you want to change value of shared_media paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/conf/enp1s0/shared_media`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.conf.enp1s0.shared_media=$value
			echo "$green net.shared_media paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi



if [ "$parameter" == secure_redirects ];then
	echo "secure_redirects => Packet resend using secure interface [ for more Info press i]"
	read info
	if [ "$info" == i ];then
		echo "The secure_redirects parameter accepts ICMP redirect messages only for a gateway
		listed in the default gateway list."
	fi
	printf "Do you want to change value of secure_redirects paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/conf/enp1s0/secure_redirects`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.conf.enp1s0.secure_redirects=$value
			echo "$green net.secure_redirects paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi

if [ "$parameter" == accept_redirects ];then
	echo "accept_redirects => Packet resend on same interface on an ICMP redirect [ for more Info press i]"
	printf "Do you want to change value of accept_redirects paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/conf/enp1s0/accept_redirects`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.conf.enp1s0.accept_redirects=$value
			echo "$green net.accept_redirects paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi



if [ "$parameter" == mc_forwarding ];then
	echo "mc_forwarding => Packet resend using secure interface [ for more Info press i]"
	read info
	if [ "$info" == i ];then
		echo " $orange The mc_forwarding parameter enables or disables multicast forwarding on this
		interface."
	fi
	printf "Do you want to change value of mc_forwarding paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/conf/enp1s0/mc_forwarding`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.conf.enp1s0.mc_forwarding=$value
			echo "$green net.mc_forwarding paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi



if [ "$parameter" == forwarding ];then
	echo "forwarding => IP forwarding"
	printf "Do you want to change value of forwarding paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/conf/enp1s0/forwarding`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.conf.enp1s0.forwarding=$value
			echo "$green net.forwarding paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi




# Routing
# Sysctl Prefix: net.ipv4.route
# /proc Prefix: /proc/sys/net/route/


if [ "$parameter" == error_burst ];then
	echo "error_burst => Time before logging a warning message"
	printf "Do you want to change value of error_burst paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/route/error_burst`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.route.error_burst.error_burst=$value
			echo "$green net.error_burst paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi





if [ "$parameter" == error_cost ];then
	echo "error_cost => Cost factor for logging a warning message"
	printf "Do you want to change value of error_cost paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/route/error_cost`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.route.error_cost.error_cost=$value
			echo "$green net.error_cost paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi





if [ "$parameter" == max_size ];then
	echo "max_size => Maximum size of routing cache"
	printf "Do you want to change value of max_size paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/route/max_size`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.route.max_size.max_size=$value
			echo "$green net.max_size paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi


if [ "$parameter" == max_size ];then
	echo "max_size => Maximum size of routing cache"
	printf "Do you want to change value of max_size paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/route/max_size`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.route.max_size.max_size=$value
			echo "$green net.max_size paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi




if [ "$parameter" == max_delay ];then
	echo "max_delay => Maximum delay in seconds for flushing routing cache"
	printf "Do you want to change value of max_delay paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/route/max_delay`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.route.max_delay.max_delay=$value
			echo "$green net.max_delay paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi



if [ "$parameter" == min_delay ];then
	echo "min_delay => Minimum delay in seconds for flushing routing cache"
	printf "Do you want to change value of min_delay paramater?(y/n)"
	read response

	if [ "$response" == y ];then
		current_parameter=`cat /proc/sys/net/ipv4/route/min_delay`
		echo "current value is $current_parameter"
		printf "Enter value you want:"
		read value
		if [ "$value" ];then
			sudo sysctl -w net.ipv4.route.min_delay.min_delay=$value
			echo "$green net.min_delay paramater changed [ OK ]"
		else
			echo "$orange Please Enter Valid Number"
		fi
	elif [ "$response" == n ];then
		echo "$blue You Dont want to change The value"
	else
		echo "$red Please Enter valid Value!!!"
	fi
fi



